@startuml

title Architecture locale 3-tier

node "Machine utilisateur N" {
  component "Navigateur Web"
}

node "Serveur Node.js N" {
  component "Express.js (API & Vue)"
  component "TypeORM"
}

database "PostgreSQL"

"Navigateur Web" --> "Express.js (API & Vue)" : HTTP (REST/EJS)
"Express.js (API & Vue)" --> "TypeORM" : appels ORM
"TypeORM" --> "PostgreSQL" : ORM (pg driver)

@enduml