@startuml

title Architecture locale 2-tier

node "Machine utilisateur" {
  component "index.js (Node.js CLI)"
  component "TypeORM"
}

database "fichier SQLite"

"index.js (Node.js CLI)" --> "TypeORM" : appels services/metier
"TypeORM" --> "fichier SQLite" : ORM (sqlite3 driver)

@enduml