services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    # On build l'image à partir du Dockerfile local
    build:
      context: .
      dockerfile: Dockerfile
    image: log430-labo:latest
    container_name: log430-labo-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    # Monte votre code et préserve node_modules installé dans l'image
    volumes:
      - ./:/LOG430-labo
      - /LOG430-labo/node_modules
    # Ici on enchaîne build TS, build CSS et lancement dev
    command: sh -c "npm run dev:web:docker"
    depends_on:
      - db

volumes:
  pgdata: