services:
  # FRONTEND
  frontend:
    build: ./frontend
    env_file: ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - auth-service-1
      - auth-service-2
      - inventory-service-1
      - inventory-service-2
      - products-service-1
      - products-service-2
      - sales-service-1
      - sales-service-2
      - store-service-1
      - store-service-2
      - saga-orchestrator-1
      - saga-orchestrator-2
    networks:
      - microservices
    volumes:
      - ./frontend/src:/frontend/src
      - ./frontend/public:/frontend/public
      - ./frontend/package.json:/frontend/package.json
      - ./frontend/package-lock.json:/frontend/package-lock.json
    command: sh -c "npm install && npm run dev"
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /frontend/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  # AUTH SERVICE
  auth-service-1:
    build: ./services/auth
    env_file: ./services/auth/.env
    ports:
      - "3101:3000"
    depends_on:
      - auth-db
    networks:
      - microservices
    command: sh -c "npm run migration:run && npm run seed && npm run dev"
    develop:
      watch:
        - action: sync
          path: ./services/auth/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/auth/package.json

  auth-service-2:
    build: ./services/auth
    env_file: ./services/auth/.env
    ports:
      - "3102:3000"
    depends_on:
      - auth-db
    networks:
      - microservices
    command: sh -c "npm run dev"
    develop:
      watch:
        - action: sync
          path: ./services/auth/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/auth/package.json

  auth-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    networks:
      - microservices

  # INVENTORY SERVICE
  inventory-service-1:
    build: ./services/inventory
    env_file: ./services/inventory/.env
    ports:
      - "3201:3000"
    depends_on:
      - inventory-db
    networks:
      - microservices
    command: sh -c "npm run migration:run && npm run seed && npm run dev"
    develop:
      watch:
        - action: sync
          path: ./services/inventory/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/inventory/package.json

  inventory-service-2:
    build: ./services/inventory
    env_file: ./services/inventory/.env
    ports:
      - "3202:3000"
    depends_on:
      - inventory-db
    networks:
      - microservices
    command: sh -c "npm run dev"
    develop:
      watch:
        - action: sync
          path: ./services/inventory/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/inventory/package.json

  inventory-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_pass
      POSTGRES_DB: inventory_db
    volumes:
      - inventory_pgdata:/var/lib/postgresql/data
    networks:
      - microservices

  # PRODUCTS SERVICE
  products-service-1:
    build: ./services/products
    env_file: ./services/products/.env
    ports:
      - "3301:3000"
    depends_on:
      - products-db
    networks:
      - microservices
    command: sh -c "npm run migration:run && npm run seed && npm run dev"
    develop:
      watch:
        - action: sync
          path: ./services/products/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/products/package.json

  products-service-2:
    build: ./services/products
    env_file: ./services/products/.env
    ports:
      - "3302:3000"
    depends_on:
      - products-db
    networks:
      - microservices
    command: sh -c "npm run dev"
    develop:
      watch:
        - action: sync
          path: ./services/products/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/products/package.json

  products-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: products_user
      POSTGRES_PASSWORD: products_pass
      POSTGRES_DB: products_db
    volumes:
      - products_pgdata:/var/lib/postgresql/data
    networks:
      - microservices

  # SALES SERVICE
  sales-service-1:
    build: ./services/sales
    env_file: ./services/sales/.env
    ports:
      - "3401:3000"
    depends_on:
      - sales-db
    networks:
      - microservices
    command: sh -c "npm run migration:run && npm run seed && npm run dev"
    develop:
      watch:
        - action: sync
          path: ./services/sales/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/sales/package.json

  sales-service-2:
    build: ./services/sales
    env_file: ./services/sales/.env
    ports:
      - "3402:3000"
    depends_on:
      - sales-db
    networks:
      - microservices
    command: sh -c "npm run dev"
    develop:
      watch:
        - action: sync
          path: ./services/sales/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/sales/package.json

  sales-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: sales_user
      POSTGRES_PASSWORD: sales_pass
      POSTGRES_DB: sales_db
    volumes:
      - sales_pgdata:/var/lib/postgresql/data
    networks:
      - microservices

  # STORE SERVICE
  store-service-1:
    build: ./services/store
    env_file: ./services/store/.env
    ports:
      - "3501:3000"
    depends_on:
      - store-db
    networks:
      - microservices
    command: sh -c "npm run migration:run && npm run seed && npm run dev"
    develop:
      watch:
        - action: sync
          path: ./services/store/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/store/package.json

  store-service-2:
    build: ./services/store
    env_file: ./services/store/.env
    ports:
      - "3502:3000"
    depends_on:
      - store-db
    networks:
      - microservices
    command: sh -c "npm run dev"
    develop:
      watch:
        - action: sync
          path: ./services/store/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/store/package.json

  store-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: store_user
      POSTGRES_PASSWORD: store_pass
      POSTGRES_DB: store_db
    volumes:
      - store_pgdata:/var/lib/postgresql/data
    networks:
      - microservices

  # SAGA ORCHESTRATOR SERVICE
  saga-orchestrator-1:
    build: ./services/saga-orchestrator
    environment:
      - DB_HOST=saga-orchestrator-db
      - DB_PORT=5432
      - DB_USER=saga_user
      - DB_PASSWORD=saga_pass
      - DB_NAME=saga_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3601:3000"
    depends_on:
      - saga-orchestrator-db
    networks:
      - microservices
    command: sh -c "npm run migration:run && npm run seed && npm run dev"
    develop:
      watch:
        - action: sync
          path: ./services/saga-orchestrator/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/saga-orchestrator/package.json

  saga-orchestrator-2:
    build: ./services/saga-orchestrator
    environment:
      - DB_HOST=saga-orchestrator-db
      - DB_PORT=5432
      - DB_USER=saga_user
      - DB_PASSWORD=saga_pass
      - DB_NAME=saga_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3602:3000"
    depends_on:
      - saga-orchestrator-db
    networks:
      - microservices
    command: sh -c "npm run dev"
    develop:
      watch:
        - action: sync
          path: ./services/saga-orchestrator/src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./services/saga-orchestrator/package.json

  saga-orchestrator-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: saga_user
      POSTGRES_PASSWORD: saga_pass
      POSTGRES_DB: saga_db
    volumes:
      - saga_pgdata:/var/lib/postgresql/data
    networks:
      - microservices

  # KONG API GATEWAY
  kong:
    image: kong:3.4
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong.yml
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./kong.yml:/kong.yml
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - microservices

  # REDIS
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - microservices

  # PROMETHEUS
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      microservices:
        aliases:
          - prometheus


  # GRAFANA
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3006:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - microservices

  # NGINX
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    networks:
      - microservices
    depends_on:
    - frontend
    - prometheus
    - grafana
    restart: always

volumes:
  frontend:
  auth_pgdata:
  inventory_pgdata:
  products_pgdata:
  sales_pgdata:
  store_pgdata:
  pgdata:
  grafana_data:
  node_modules:
  saga_pgdata:

networks:
  microservices: