services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: labuser
      POSTGRES_PASSWORD: labpassword
      POSTGRES_DB: labdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: log430-labo:latest
    container_name: log430-labo-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./:/LOG430-labo
      - /LOG430-labo/node_modules
    command: sh -c "npm run build:css -- --watch & npm run dev:web"
    depends_on:
      - db

volumes:
  pgdata: