global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth'
    static_configs:
      - targets: ['auth-service-1:3000', 'auth-service-2:3000']
        labels:
          service: 'auth'

  - job_name: 'inventory'
    static_configs:
      - targets: ['inventory-service-1:3000', 'inventory-service-2:3000']
        labels:
          service: 'inventory'

  - job_name: 'products'
    static_configs:
      - targets: ['products-service-1:3000', 'products-service-2:3000']
        labels:
          service: 'products'

  - job_name: 'sales'
    static_configs:
      - targets: ['sales-service-1:3000', 'sales-service-2:3000']
        labels:
          service: 'sales'

  - job_name: 'store'
    static_configs:
      - targets: ['store-service-1:3000', 'store-service-2:3000']
        labels:
          service: 'store'