global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth'
    static_configs:
      - targets: ['localhost:80']
        labels:
          service: 'auth'
    metrics_path: /auth/metrics

  - job_name: 'inventory'
    static_configs:
      - targets: ['localhost:80']
        labels:
          service: 'inventory'
    metrics_path: /inventory/metrics

  - job_name: 'products'
    static_configs:
      - targets: ['localhost:80']
        labels:
          service: 'products'
    metrics_path: /products/metrics

  - job_name: 'sales'
    static_configs:
      - targets: ['localhost:80']
        labels:
          service: 'sales'
    metrics_path: /sales/metrics

  - job_name: 'store'
    static_configs:
      - targets: ['localhost:80']
        labels:
          service: 'store'
    metrics_path: /store/metrics