global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth'
    static_configs:
      - targets: ['http://kong:8000/auth']
        labels:
          service: 'auth'
    metrics_path: /metrics

  - job_name: 'inventory'
    static_configs:
      - targets: ['http://kong:8000/inventory']
        labels:
          service: 'inventory'
    metrics_path: /metrics

  - job_name: 'products'
    static_configs:
      - targets: ['http://kong:8000/products']
        labels:
          service: 'products'
    metrics_path: /metrics

  - job_name: 'sales'
    static_configs:
      - targets: ['http://kong:8000/sales']
        labels:
          service: 'sales'
    metrics_path: /metrics

  - job_name: 'store'
    static_configs:
      - targets: ['http://kong:8000/store']
        labels:
          service: 'store'
    metrics_path: /metrics