global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'app'
    static_configs:
      - targets: ['log430-labo-app:3000']

  - job_name: 'loadbalancer'
    static_configs:
      - targets: ['log430-labo-nginx:80']