@startuml modules-organisation

title Organisation des modules

package "LOG430-labo" {
    package "docs" as D {
        class development
        class logical
        class physical
        class process
        class useCase
        class README
    }
    package "frontend" as F {
        package public {
            class css
            class js
        }
        package src {
            class routes
            class views
        }
    }
    package "provisioning" as P {
        package dashboard {
            class default
            class grafana
        }
        package datasource {
            class datasource
        }
    }
    package "services" as S {
        package auth {
        }
        package inventory {
        }
        package products {
        }
        package sales {
        }
        package store {
        }
    }
}

physical -[hidden]right- process
process -[hidden]right- useCase
useCase -[hidden]right- README
D -[hidden]down- F
F -[hidden]down- P
P -[hidden]down- S

@enduml
