@startuml
skinparam style strictuml

actor "Opérateur" as Operateur
participant "CLI" as UI
participant VenteService
participant ProduitRepo
participant VenteRepo

Operateur -> UI : startSale()
UI -> VenteService : createSale()
VenteService -> ProduitRepo : findById(id)
ProduitRepo --> VenteService : produit
VenteService -> VenteRepo : save(vente)
VenteRepo --> VenteService : confirmation
VenteService --> UI : printReceipt()
@enduml